### ISSUE TITLE
flexbox layout doesn't work

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#1522]
Flexbox seems to be broken in wkhtmltopdf.

Here's a test case, which renders correctly in current versions of Chrome, Firefox, and Internet Explorer. wkhtmltopdf renders it as if the flex properties were not present.

Tested with the 0.12 Windows 32-bit download as found on http://wkhtmltopdf.org/ (wkhtmltox-win32_0.12.0-03c001d.exe). As you can see I tried using the -webkit- prefixes and they didn't help. 

```
<!DOCTYPE html>
<html><head><title>Flexbox test</title>
<style>
body {
  width: 800px;
  border: 2px solid green;
}
.flexrow {
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  display: -webkit-flex;
  -webkit-flex-direction: row;
  -webkit-justify-content: space-between;
}
.flexrow > div {
  background-color: yellow;
  border: 1px dashed black;
}
</style>
</head>
<body>
  <div class="flexrow">
    <div>This is<br>item 1</div>
    <div>This is<br>item 2</div>
    <div>This is<br>item 3</div>
    <div>This is<br>item 4</div>
    <div>This is<br>item 5</div>
  </div>
</body>
</html>
```

**Comment by mdPlusPlus** [comment]
So, can we count on flexbox support anytime soon?

**Comment by ashkulz** [comment]
Try the `0.13 alpha` builds.

**Comment by alonfixler** [comment]
Hey, I'm using 0.13 alpha. Using display:flex doesn't seem to work...

**Comment by foundryspatial-duncan** [comment]
For those using version 0.12.2.1 (with patched qt), you *can* use the old `display:box` syntax.

If you're using autoprefixer set for `Chrome >= 13`, 
This css:
```css
.foo {
    display: flex;
    justify-content: center;
}
```

Outputs like this:
```css
.foo {
    display: -webkit-box; // wkhtmltopdf uses this one
    display: -webkit-flex;
    display: flex;
    -webkit-box-pack: center; // wkhtmltopdf uses this one
    -webkit-justify-content: center;
            justify-content: center;
}
```
