### ISSUE TITLE
Font face problem on 0.12.0

### ISSUE THREAD

**Issue by rutcreate** [wkhtmltopdf/wkhtmltopdf#1622]
I've tried version 0.10.0 rc2 before. It works great but table header repeating still not support. Then I know that table header repeating is supported on version 0.12.0 (with https://github.com/carloespinosa/wkhtmltopdf-table-fix) and I change to use this version but font face does not work with the same code. Do I need to do something more?

Here is my css code:

``` css
@font-face {
    font-family: 'THSarabunNew';
    src: url('../fonts/thsarabunnew-webfont.eot');
    src: url('../fonts/thsarabunnew-webfont.eot?#iefix') format('embedded-opentype'),
         url('../fonts/thsarabunnew-webfont.woff') format('woff'),
         url('../fonts/thsarabunnew-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
body {
  font-family: 'THSarabunNew', sans serif;
}
```

I try Google Fonts. It does not work neither.

``` html
<link href='http://fonts.googleapis.com/css?family=Ceviche+One' rel='stylesheet' type='text/css'>
```

``` css
body {
    font-family: 'Ceviche One', cursive;
}
```

PS: I am currently using MacBook but finally it will be used on Linux server.
