### ISSUE TITLE
background gradients stepped on <th> tags when using a border

### ISSUE THREAD

**Issue by rsteinwand** [wkhtmltopdf/wkhtmltopdf#1778]
Here's another problem with th tags. (last one I submitted was with sprite background images, marked as won't fix until an updated QT).

Here's the css: 

``` css
.valign-top{vertical-align:top}
.valign-bottom{vertical-align:bottom}
th{color:#fff;background:-webkit-gradient(linear,left top,left bottom,color-stop(0%,rgb(64,128,176)),color-stop(100%,rgb(1,73,129)));background:linear-gradient(to bottom,rgb(64,128,176) 0%,rgb(1,73,129) 100%);border-right:1px solid #8EB1CB}
```

Here's the html:

``` html
<tr class="valign-bottom"><th style="width:100px">Variable</th><th class="center">Field Length</th><th>Value</th></tr>
<tr><td>response1, </td><td class="center" rowspan="3">1</td>
<td rowspan="3" class="valign-top">Values derived from the multifactor grid coordinates (challenges 1-3) obtained in the first hit. (example: the value for challenge1 is &quot;F3&quot;. From the card, find column &quot;F&quot; and find where it intersects with row &quot;3&quot;. Use that value for response1.)</td></tr>
<tr><td>response2, </td></tr>
<tr><td>response3 </td></tr>
```

Here's what the background should look like:
![th-good](https://cloud.githubusercontent.com/assets/6683417/3273601/59acccd8-f326-11e3-91d7-9bbc6daf78fd.PNG)

... but it ends up looking like this:
![th-bad](https://cloud.githubusercontent.com/assets/6683417/3273561/014569e2-f326-11e3-99bb-75a3a6880ce2.PNG)

Now if I remove the border from the th tags, it'll work fine. If I use a bottom border, it'll work fine.

Hope this makes it into the 12.1 final build.

Thanks.
