### ISSUE TITLE
@Font-face not rendered on 0.12.1 - Maverick

### ISSUE THREAD

**Issue by CharlieBreval** [wkhtmltopdf/wkhtmltopdf#1862]
Hello, 1 week ago, I just changed my development environment, switching my Fedora to a Maverick. I built a pdf on Fedora, with good fonts, everything was fine. Now I retry the same pdf on Mac OS, all the fonts are broken.

I'm using wkhtmltopdf on a Symfony2 application.
It looks like wkhtmltopdf built for mac Os doesn't support some precise fonts (here : itckabel-book-webfont )

You can see my code here : 
The html : 

``` html

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <base href="http://{{app.request.host}}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('/bundles/belmsite/css/pdf.css') }}">
</head>

```

And my css : 

``` css
@font-face {
    font-family: 'itc_kabel_bookregular';
    src: url('../fonts/itckabel-book-webfont.eot');
    src: url('../fonts/itckabel-book-webfont.eot?#iefix') format('embedded-opentype'),
         url('../fonts/itckabel-book-webfont.woff') format('woff'),
         url('../fonts/itckabel-book-webfont.ttf') format('truetype'),
         url('../fonts/itckabel-book-webfont.svg#itc_kabel_bookregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

The result should be this (built with a fedora) : 
http://www.belm.fr/pdf/ecume

But the result is this : 
http://www.charliebreval.com/ecume.pdf
