### ISSUE TITLE
thead overlaps tr on page break

### ISSUE THREAD

**Issue by oramospt** [wkhtmltopdf/wkhtmltopdf#1907]
hy, 

im creating a pdf that contains several pages and i want that the thead repeats across the pages of the pdf, but the thead is overlaping the tr on the page break.

How can i do this?

I'm currently using the 12.1 but i tried already with the 12.2 without success.

thanks in advance

**Comment by joshuapinter** [comment]
Full solution from #1770: 

```css
thead { display: table-header-group }
tfoot { display: table-row-group }
tr    { page-break-inside: avoid }
```

Thanks to @jwynia from [his comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1770#issuecomment-73530576).
