### ISSUE TITLE
The letter O in font not rendering correctly

### ISSUE THREAD

**Issue by mangopop** [wkhtmltopdf/wkhtmltopdf#2022]
Hi, 

Hopefully someone may be able to shed some light on this?

I've got a problem with just one font character rendering badly. 

Here is the problem character (O)
![bio](https://cloud.githubusercontent.com/assets/5812570/4792842/9a07174c-5de9-11e4-8968-6ec3bc3053f0.png)

The font type is Kabel and it's loaded using font-face css like so:

```
@font-face {
    font-family: 'KabelLTStd-Heavy';
    src: url('/webfonts/2BA23B_14_0.eot');
    src: url('/webfonts/2BA23B_14_0.eot?#iefix') format('embedded-opentype'),
url('/webfonts/2BA23B_14_0.woff') format('woff'), url('/webfonts/2BA23B_14_0.ttf') format('truetype');
}
```

and called in with 
     font-family: KabelLTStd-Heavy, helvetica, sans-serif;

Is this the fonts problem? Which font does wkhtmltopdf use given the options above?

I've installed the fonts on the OS, but this hasn't made a difference.

Here are some details of my envroment:
wkhtmltopdf 0.12.1 (with patched qt)
Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-36-generic x86_64)
also tried on version 14.*

Could it be a problem with the OS I'm using? Or the version of wkhtmltopdf? 

Any help would be greatly appreciated.

**Comment by daviferreira** [comment]
Having the same issue with Helvetica on Ubuntu Server. Works fine on Mac.

**Comment by ashkulz** [comment]
Can you check with the [0.13-alpha](http://sourceforge.net/projects/wkhtmltopdf/files/0.13.0-alpha/) Windows or Debian Wheezy version (not headless yet; run via `xvfb-run`) whether it looks OK?

**Comment by mangopop** [comment]
Hi,

Yes that has worked!

**Comment by ashkulz** [comment]
@baruchel, @daviferreira: I assume that it will work for you on `0.13.0` too -- if it doesn't help, please report back.

**Comment by bonny** [comment]
Using 0.13 worked for me. I had this problem with 0.12.1 on an headless Ubuntu 14. 

(Opacity/transparency stopped working however when switching 0.13, but I saw that was mentioned in another issue.)

**Comment by andrewjlow** [comment]
Is there any chance of a 0.12.x fix for this? I have been having a hard time trying to get the alpha version running on my Amazon EC2 instance...

**Comment by pomm0** [comment]
I got the same problem, any chance of a 0.12.x fix?

**Comment by artifilabs** [comment]
When will the version 0.13 be released with patched qt.

**Comment by allisterk** [comment]
Note that this was fixed by using OTF rather than TTF on our systems using 0.12.4

**Comment by ImArtur** [comment]
@ashkulz are there any informations about this?

**Comment by dominiceden** [comment]
Having same issue on Ubuntu 16.04.4 LTS - font is Nunito (Google Fonts)

<img width="783" alt="screen shot 2018-08-04 at 16 57 20" src="https://user-images.githubusercontent.com/6367692/43678240-8d72239e-9807-11e8-8b39-f9e6fd6592c0.png">

**Comment by juresrpcic** [comment]
Had the same issue on Ubuntu 18.04 LTS - using wkhtmltopdf 0.12.5 (with patched qt).

I installed wkhtmltopdf with instructions [here](https://gist.github.com/srmds/2507aa3bcdb464085413c650fe42e31d) (worked great - includes libpng12-0 dependency some people have issues with and works properly with https sources).

Was able to fix the glyph artifacts it by getting OTF versions of fonts (for Google fonts, you can find them here: [https://github.com/googlefonts](https://github.com/googlefonts)).

This is an example CSS font-face for a two weights using OTF (Rubik Google font):

```css
@font-face {
	font-family: 'Rubik';
	font-style: normal;
	font-weight: 300;
	src: local('Rubik Light'), local('Rubik-Light'),
		url('https://yourserver.com/pdf/rubik/Rubik-Light.otf') format('opentype');
}
@font-face {
	font-family: 'Rubik';
	font-style: normal;
	font-weight: 400;
	src: local('Rubik'), local('Rubik-Regular'),
		url('https://yourserver.com/pdf/rubik/Rubik-Normal.otf') format('opentype');
}
```
