### ISSUE TITLE
Avoid page break after heading

### ISSUE THREAD

**Issue by vevisystems** [wkhtmltopdf/wkhtmltopdf#2215]
We don't like to have a page break after h2, we rather prefer to make the break just before, and start the new page with the heading. However, even using page-break-after: avoid; it continues to happen regularly.

Is there any way to avoid this?

**Comment by romj** [comment]
Same problem here. The following CSS

```CSS
@media print {
    h2{
    	page-break-after: avoid;
    }
}
```
Does not work.
