### ISSUE TITLE
How can i add footer at the bottom of the page wkhtmltopdf

### ISSUE THREAD

**Issue by usamamashkoor** [wkhtmltopdf/wkhtmltopdf#2238]
Here is its proper link of question

http://stackoverflow.com/questions/28963063/how-can-i-add-footer-at-the-bottom-of-the-page-wkhtmltopdf

I am using wkhtmltopdf to genereate reports now i have encounterd with a situation where i have to show footer at the bottom of the page i have tried to solve this with css it works on simple page but not on my wkhtmltopdf generated page here is my HTML code

```html
<footer id="footer">
    <p>Hello World</p>
</footer>
```

And my css is this

```css
# footer {
    position:fixed;
    height:50px;
    background-color:red;
    bottom:0px;
    left:0px;
    right:0px;
    margin-bottom:0px;
}
```

I have also tried this code given on wkhtmltopdf page
```html
<script>
            window.onload = function() {
            var vars = {};
            var x = document.location.search.substring(1).split('&');
            for (var i in x) {
            var z = x[i].split('=', 2);
            [z[0]] = unescape(z[1]);
           }

           if current page number == last page number
        if (vars['page'] == vars['topage']) {
        document.querySelectorAll('#footer')[0].textContent = 'extra text  here';
        }
            };
</script>
```

Note This i am not using cmd command i am using codigniter is their any option like
```php
$this->wkhtmltopdf->setOptions(array(
    'orientation' => 'landscape'
));
```

Thanks in advance
