### ISSUE TITLE
Problem with base64 encoded fonts

### ISSUE THREAD

**Issue by kenrayner** [wkhtmltopdf/wkhtmltopdf#2570]
Hello
I'm having trouble when using two specific fonts (encoded base64 in the CSS).

So, here is my test HTML:
```html
<html>
<head>
	<meta charset="utf-8">	
	<link rel="stylesheet" type="text/css" href="render.css">
</head>
<body>
<h4>Test Main Title in h4</h4>
<h5>Secondary Title in h5</h5>
<P>Normal Text</P>
</body>
</html>
```
And here is the CSS (I've removed the base64 string to save space):

```CSS
h4 {
  font-family: 'Av1'; 
  font-size:1.6em;
}

p {
  font-family: 'Av1'; 
  font-size:0.85em;
}

h5 {
  font-family: 'Av2';
  font-size:0.9em;
}

@font-face {
    font-family: 'Av1';
    src: url(data:font/truetype;charset=utf-8;base64,...);
}

@font-face {
    font-family: 'Av2';
    src: url(data:font/truetype;charset=utf-8;base64,...);
}
```

Which renders fine in a browser (I've removed some styling & positioning from the CSS above):

![screenshot 2015-09-10 at 12 16 19](https://cloud.githubusercontent.com/assets/5695602/9786928/e3277996-57b5-11e5-9d96-ebe6184224a3.png)

But when I generate a PDF from it, the "Av2" font (the "demi bold" one) doesn't render:

![screenshot 2015-09-10 at 12 20 36](https://cloud.githubusercontent.com/assets/5695602/9786986/757a83f6-57b6-11e5-8bc5-5afb4ac80653.png)

The font is Avenir Next Condensed (yes, we're licenced to use it!) and I'm stuck for ideas now!

Many thanks

Ken
