### ISSUE TITLE
disable: href content is added to content in brackets

### ISSUE THREAD

**Issue by jobe451** [wkhtmltopdf/wkhtmltopdf#2649]
when I have HTML to render like
```html
<a href="http://www.link.com">http://www.link.com</a>
```
It renders as:
> http://www.link.com (http://www.link.com)

I would expect to see:
> http://www.link.com

WKHTMLTOPDF adds the href to the content in brackets. How can I disable this behaviour. ?

**Comment by Maks3w** [comment]
Are you using twbs bootstrap?

https://github.com/twbs/bootstrap/blob/10606a73bcbfc6c723d60e2a1069c921afff0d2a/less/print.less#L23-L25

```css
    a[href]:after {
        content: " (" attr(href) ")";
    }
```
