### ISSUE TITLE
Not divide image

### ISSUE THREAD

**Issue by brucejcw** [wkhtmltopdf/wkhtmltopdf#2898]
My image will be divided into two parts in two pdf pages, How to let the whole image shown in the next pdf page?  
I'm using html tag `<img src`  

Thank you

**Comment by luzfcb** [comment]
```css
.not-divide-image {
     display: block;
}
```

```
<img src="...." alt="...." class="not-divide-image">
```
