### ISSUE TITLE
display: table-header-group; not working

### ISSUE THREAD

**Issue by SilexNoobie** [wkhtmltopdf/wkhtmltopdf#3047]
I wonder if somebody me please. I'm using wkhtmltopdf to create a pdf of a page with lots of tables in it. The pdf is being created and all of the styles are working expect for display: head-table-group. I've even added !important to it but that's still not working. It adds a blank th but has no text at all. I've tried using a default font and changing the size but that doesn't make a difference.

The css I'm using is:

```css
ahead {
    display: table-header-group!important;
    font-size: 12px!important;
    font-family: Helvetica, sans-serif!important;
    color: #000!important;
}
```

and the html is:

```html
<div class="main">
<div class="table_div">
<div class="table">
<table class="collapsable_table">
<thead>
<tr>
<th>Title</th>
<th>Artist</th>
<th>Genre</th>
<th>Country</th>
<th>Stock level</th>
<th>Year</th>
</tr>
</thead>
<tbody>

<tr class="album_full">
<td><a href="#">True Blue</a></td>
<td><a href="#">Madonna</a></td>
<td>Pop</td>
<td>USA</td>
<td>25%</td>
<td>1984</td>
</tr>

<tr class="album_full">
<td><a href="#">Bad</a></td>
<td><a href="#">Michael Jackson</a></td>
<td>Pop</td>
<td>USA</td>
<td>50%</td>
<td>1988</td>
</tr>

...................

</tbody>
</table>
</div>
</div>
</div>
```

Thanks for any help anybody can offer
