### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by edap** [wkhtmltopdf/wkhtmltopdf#3111]
I've a segmentation fault running this command with the 0.12.3 version for mac os and 0.12.1 for linux:

```bash
wkhtmltox/bin/wkhtmltopdf --javascript-delay 1000 --enable-toc-back-links  --margin-bottom 20 --margin-left 0 --margin-right 0 --margin-top 50 --header-spacing 7 --disable-smart-shrinking --header-html /vagrant/rails_app/pdf/header.html --footer-html /vagrant/rails_app/pdf/footer.html toc --xsl-style-sheet /vagrant/rails_app/pdf/toc.xls /vagrant/rails_app/pdf/file.html /vagrant/rails_app/pdf/tmp.pdf
```

The strange thing is that if I change the content of the file `file.html`, precisely line 112, the `line-height` value, from 1.3 to 1.4

from:

```css
.reader-handout-result__text,
.reader-handout-summary__text,
.reader-handout__date {
	line-height: 1.3;
	font-size: 11px;
	text-align: justify;
}
```

to :

```css
.reader-handout-result__text,
.reader-handout-summary__text,
.reader-handout__date {
	line-height: 1.4;
	font-size: 11px;
	text-align: justify;
}
```

The bug is gone.

As github does not allow to attach files, I've uploaded the html files to wetransfer https://we.tl/TUxN3bDvC0 in order to reproduce the bug locally.
