### ISSUE TITLE
CSS Variables Support

### ISSUE THREAD

**Issue by caleywoods** [wkhtmltopdf/wkhtmltopdf#3253]
Let me preface this issue by saying that I'm not sure exactly where the falldown occurs with WKHTMLTOPDF [using CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and that I have just fallen back to not using them in the CSS linked to my views that create PDFs so I don't consider this an urgent need by any means.

I have a simple Blade template (laravel, using [laravel-snappy](https://github.com/barryvdh/laravel-snappy)) which relies on an external stylesheet. Within this stylesheet I used a single CSS variable similar to this:
```css
    :root {
        --repeatable-color: #000;
    }

    #div {
        background-color: var(--repeatable-color);
    }
```

Whether you use relative linking or absolute linking to the external file or you use inline CSS WKHTMLTOPDF will not apply the color (or any other directive I would guess) used from the CSS variable.

Nothing too major - Just something I thought might be useful but didn't know if this was a WKHTMLTOPDF issue or a QT issue. I made sure it wasn't an issue with the PHP wrapper I was using by trying the command line version of wkhtmltopdf and the issue persisted.
