### ISSUE TITLE
-webkit-gradient not working in --header-html

### ISSUE THREAD

**Issue by phil294** [wkhtmltopdf/wkhtmltopdf#3408]
The following code snippet 
	<!DOCTYPE html>
	<html>
	<head></head>
	<body>
	<div id="header" style="background: -webkit-linear-gradient(left, black, blue);">
		<p>Text</p>
	</div>
	</body>
	</html>
Will render a nice gradient usually (note that the standard syntax `linear-gradient` is not recognized by wkhtmlpdf, but that's neglectable). However, when used inside a `--header-html header.html`, the background will **not** be visible. 

Workaround: Could not find any. Will need to use a background-image now.
Best regards,

**Comment by marianopeck** [comment]
Did you finally found something? I am facing the same problem...

**Comment by phil294** [comment]
@marianopeck No, unfortunately I have not. I will be using either a static pre-rendered background image, or not use wkhtmltopdf at all: make use of css' `@media` queries and simply let the browser generate a pdf via ctrl+p.

**Comment by mk-pmb** [comment]
I'm here because my

```css
.headline-bg {
  background-image: linear-gradient(to right, rgba(0,0,0,0.4), rgba(0,0,0,0));
}
```

has no effect in wkhtmltopdf, while it works as expected in Firefox.
Note the "to" in my `to right`; without that, Firefox can't understand it either, so double-check whether you'd need that with `-webkit-linear-gradient` as well.

**Comment by mk-pmb** [comment]
```css
.headline-bg {
  background-image: -webkit-linear-gradient(   left,  rgba(0,0,0,0.4), rgba(0,0,0,0));
  background-image:         linear-gradient(to right, rgba(0,0,0,0.4), rgba(0,0,0,0));
}
```
