### ISSUE TITLE
Images not displayed when using bootstrap visibility classes

### ISSUE THREAD

**Issue by wkusr9000** [wkhtmltopdf/wkhtmltopdf#3495]
I am using bootstraps visibility helpers to hide images in the browser and to display them again in print mode:

css
```css
// original bootstrap css
.visible-print-block {
  display: none !important;
}
@media print {
  .visible-print-block {
    display: block !important;
  }
}

.logo {
  background-image: url(data:image/jpeg;base64 [...]);
  width: 130px;
  height: 130px;
}
```

html
```html
<div class="visible-print-block">
    ...
    <div class="logo"></div>
    ...
</div>
```

The image does not show up in the pdf, although the space for it is reserved. It looks like the `display: none` (although immediately overwritten by the `@media print` rule) stops the engine from loading any images within the block. This only happens if the `visible-print-block` class is set on a parent element instead of the image itself.

Strangely everything works again if I put the logo somewhere outside of the hidden block like so:

html
```html
<div class="logo"></div>

<div class="visible-print-block">
    ...
    <div class="logo"></div>
    ...
</div>
```

Now both images show up correctly.

I am using wkhtmltopdf `0.12.4` with the `--print-media-type` option.
