### ISSUE TITLE
Footer doesn't render

### ISSUE THREAD

**Issue by rvandyk** [wkhtmltopdf/wkhtmltopdf#3531]
Hey, with this in my css, the footer won't render in the pdf...

```css
  footer{
background:#ccc;
position:absolute;
bottom:0;
width:100%;
padding-top:50px;
}
```

Any explainations ?
