### ISSUE TITLE
Help display Google Fonts

### ISSUE THREAD

**Issue by DarthLegiON** [wkhtmltopdf/wkhtmltopdf#3578]
Hello. I know this is a common issue but I've tried all possible solutions and no one helped.
I use several fonts on my page. Some of them work and some is not. Let me show you some examples.

Bootstrap Glyphicons - works fine. Code in bootstrap.css left untouched:
```css
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
.glyphicon {
  ...
  font-family: 'Glyphicons Halflings';
  font-style: normal;
  font-weight: normal;
  line-height: 1;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
Another font - Google Material Icons. Doesn't work.
![image](https://user-images.githubusercontent.com/11365194/28679829-11200e58-72fd-11e7-8986-11966eea5d6a.png)

```css
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'),
    url('fonts/MaterialIcons-Regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
    url('fonts/MaterialIcons-Regular.woff2') format('woff2'), /* Super Modern Browsers */
    url('fonts/MaterialIcons-Regular.woff') format('woff'), /* Modern Browsers */
    url('fonts/MaterialIcons-Regular.ttf') format('truetype'), /* Safari, Android, iOS */
    url('fonts/MaterialIcons-Regular.svg') format('svg'); /* Legacy iOS */
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  ...
  -webkit-font-feature-settings: 'liga';
  font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
I tried to left only woff font, only ttf font, inserted direct link to Google 
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
After all this manipulations font looked well in Chrome but there was only empty void in PDF. Removed src parameter - and there was text instead of icon.
![image](https://user-images.githubusercontent.com/11365194/28679762-e4011e1c-72fc-11e7-950b-34780b1145b7.png)

Google Roboto font also doesn't work. Code is similar to Material, but I cannot use direct Google link because I renamed this font in CSS for my purposes (it conflicted with local installed font). 

And last server stored font - works fine!
```css
@font-face {
  font-family: 'Fedra';
  src: url('../fonts/Fedra-Serif-A-Pro-Book.ttf');
}
```

Wkhtmltopdf version is 0.12.2 (with patched qt) installed on CentOS 6. 

I've killed whole day on this problem and hope for your help. Thanks!
