### ISSUE TITLE
Trouble with border-radius

### ISSUE THREAD

**Issue by Antonboom** [wkhtmltopdf/wkhtmltopdf#3600]
```css
.b-box {
    background: #ffffff;
    position: relative;
    border: 1px solid #dcdcdc;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    -webkit-box-shadow: 0 2px 0 0 #f0f0f0;
    box-shadow: 0 2px 0 0 #f0f0f0;
    height: inherit;
    box-sizing: border-box;
    margin-right: 20px;
    margin-bottom: 20px;
}
```
```html
<div class="b-box"></div>
```
centos-release-6-9.el6.12.3.x86_64
wkhtmltopdf 0.12.1 (with patched qt)
Using pdfkit 0.6.1 (python).

Trying to render this block causes the following error:
```
Failed to submit message: u'IOError: wkhtmltopdf exited with non-zero code -9. error:\nQFont::setPixelSize: Pixel size <= 0 (0)\nQFont::setPixelSize: Pixel size <= 0 (0)\nQFont::setPixelSize: Pixel size <= 0 (0)\nQFont::setPixelSize: Pixel size <= 0 (0)\nQFont::setPixelSize: Pixel size <= 0 (0)\nQImage: out of memory, returning null\nQImage: out of memory, returning null image\nQImage: out of memory, returning null image\n'
```

The problem is solved by cleaning border-radius:
```css
.b-box {
    -webkit-border-radius: 0px;
    border-radius: 0px;
}
```

Have any comments on this? Thanks
