### ISSUE TITLE
Empty pseudo-class hides images

### ISSUE THREAD

**Issue by sirideain** [wkhtmltopdf/wkhtmltopdf#3789]
With this CSS applied to a table, then the background image is not displayed in the cells. Changing empty to blank displays the images correctly. Both options work in a browser. The cells had other content as well.

```css
table.tData1 tbody:empty {
        display: none;
}

table.tData1 td.mid{
	background-image: url(data:image/png;base64,iVBOR...);
	background-repeat: no-repeat;
}
```
