### ISSUE TITLE
CSS selector does not work with multiple classes on one tag

### ISSUE THREAD

**Issue by elioschmutz** [wkhtmltopdf/wkhtmltopdf#3907]
If there are multiple classes on a tag, it's only possible to select this tag with the first class:

Does not work:
===========
```css
    .two {
        background-color: red;
    }
```
```html
    <div class="one two">
        james bond
    </div>
```
<img width="846" alt="bildschirmfoto 2018-05-09 um 17 27 23" src="https://user-images.githubusercontent.com/557005/39823888-4dbc66c6-53ae-11e8-84de-799d4137c85c.png">

Does work:
========
```css
    .one {
        background-color: red;
    }
```
```html
    <div class="one two">
        james bond
    </div>
```
<img width="822" alt="bildschirmfoto 2018-05-09 um 17 28 01" src="https://user-images.githubusercontent.com/557005/39823919-60ed6092-53ae-11e8-9a82-0736a864ed37.png">

Do you have a solution for this problem?
