### ISSUE TITLE
Font size not working well in pdf compare to html

### ISSUE THREAD

**Issue by thiruopti** [wkhtmltopdf/wkhtmltopdf#4068]
Hi,
Am using node js wkhtmltopdf plugin to generate pdf document from html content. Am using ckeditor to display html content with margins and export the content as pdf using wkhtmltopdf plugin.
        
         wkhtmltopdf version - 0.12.2.1
         Following configuration am used for generating pdf document
             1. --page-width  = 8 (inch)
             2. --page-height = 4 (inch)
             3. --margin-bottom =  --margin-top =  --margin-left =  --margin-right = 0 (inch)
        wkhtmltopdf --page-width 8in --page-height 4in --margin-left 0in --margin-right 0in --margin-bottom 0in --margin-top 0in --print-media-type --zoom 1.0 --dpi 96 sample-html.html sample-html.pdf

My problem is, the font size are not looking good compared than html. Am used font-size as 12pt. But in pdf it showing as 12.29pt i guess.
      Sample Style Sheet:
```css
  @font-face {
  font-family: 'Arial';
  font-style: normal;
  font-weight: 300;
  src:
    url('../fonts/Arial/arial.otf') format('otf'),
    url('../fonts/Arial/arial.woff') format('woff'),
    url('../fonts/Arial/arial.svg') format('svg'),
    url('../fonts/Arial/arial.ttf') format('ttf'),
    url('../fonts/Arial/arial.eot') format('eot');
}
.normalStyle {
        /* Font */
        /*font-family: sans-serif, Arial, Verdana, "Trebuchet MS";*/
        font-family: 'Arial';
        font-size: 12pt; /* Text color */
        color: red;
        /* Remove the background color to make it transparent */
        /*background-color: #fff;*/
        /*height:auto!important;*/
        overflow:visible!important;
    /*margin: 0.5cm auto;*/
        word-wrap: break-word;
        min-height: 100%;
}
body
{
        /* Font */
        /*font-family: sans-serif, Arial, Verdana, "Trebuchet MS";*/
        font-family: Arial;
        /*font-size: 16px;*/
/*      font-size: 12pt;*/
        line-height: 17.5px;
        /* Text color */
        color: #333;
/*        min-height: 100%;*/
        /* Remove the background color to make it transparent */
        /*background-color: #fff;*/
        /*height:auto!important;*/
/*        overflow:visible!important;*/
        /*box-sizing:border-box;*/
        margin:0;
        padding:0;
        /*background-color:red;*/
        /*margin: 20px;*/

        /*height:3.65in;*/

}
```

        Sample html file:
```html
            <!DOCTYPE html><html><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><head><link rel="stylesheet" href="Sample-pdf-stylesheet.css"></head>
<body class="document-editor" >
	<div class='normalStyle' style="letter-spacing:0px">aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccd</div>
</body>
</html>
```

       Front end output:          
![front_output](https://user-images.githubusercontent.com/16874755/44994177-0d332180-afbb-11e8-9f03-04cb8c622a27.png)

      Generated pdf output:      
[sample-html.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2346023/sample-html.pdf)

      And also the line height also not working well. somebody please suggest me a solution to fix this.
