### ISSUE TITLE
Font bold and italics bug

### ISSUE THREAD

**Issue by nikhilm492** [wkhtmltopdf/wkhtmltopdf#4070]
We are using wkhtmltopdf with a specific font called "Optima" defined in CSS using @font-face rules for each font style and font weight. Below is the @font-face rules used. The urls have been tried with data-uri as well. The files are present on disk for the below urls. But wkhtmltopdf renders italics (em tag or i tag) as bold italic always. We have tried older wkhtmltopdf versions and the bug is there as well. Can this be looked at? Our current wlhtmltopdf version is 0.12.5
```css
@font-face{
        font-family: 'Optima';
        src: url("/fonts/4_regular.TTF");
}
@font-face{
        font-family: 'Optima';
	src: url("/fonts/4_bold.TTF");
	font-weight: bold;
}			
@font-face{
	font-family: 'Optima';
	src: url("/fonts/4_italic.TTF");
	font-style: italic;
}			
@font-face{
	font-family: 'Optima';
	src: url("/fonts/4_bolditalic.TTF");
	font-weight: bold;
	font-style: italic;
}			
```
