### ISSUE TITLE
Fit image size to page

### ISSUE THREAD

**Issue by Neyri** [wkhtmltopdf/wkhtmltopdf#4692]
I am using wkhtmltopdf to create PDF documents with text of variable length and at the end append an image.
I would like the image
- height to be between two values (lets say 500px and 250px)
- height to be the higher between these two values
- to fit in one page if possible, ie if there is at least a 250px space at the end of the page insert the image, otherwise insert it into a new page
The code I used (that doesn't seem to work) is the following :
HTML
```html
<div class="images">
      <img src="img_uri" class="image"></img>
</div>
```
CSS
```css
.image{
  max-height: 500px;
  min-height: 250px;
  height:100%;
  width: auto;
}
```

Thank you for you help 😊
