### ISSUE TITLE
material Icon not working

### ISSUE THREAD

**Issue by jofvr** [wkhtmltopdf/wkhtmltopdf#4899]
**wkhtmltopdf version(s) affected**: wkhtmltoimage 0.12.6 

**OS information**

macOS 11.0.1 & Debian 9 amd 64

**Description**

Sample html with material icon not working. The icon is not display.

**How to reproduce**

Add 
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">` to an html file with an icon (for exemple `<i class="material-icons">mood</i>`).

**Expected behavior**

Icon should be displayed

**Possible Solution**

**Comment by jofvr** [comment]
Nobody has the same problem ?

**Comment by PhilterPaper** [comment]
I can reproduce the problem with wkHTMLtoPDF 0.12.5 (patched qt) on Windows 10.
```
<html>
<head>
  <title>Material icon problem</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
</head>
<body>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
	<br/> <br/>
 An html file with an icon (for example <i class="material-icons">mood</i> as you just saw).
</body>
</html>
```
The text "An html file with an icon (for example<space>" and "<space>as you just saw)." shows up (although poorly spaced) as TrueType font output. There is a large gap where an HTML browser shows a smiley face. Looking at the PDF content, the missing part is
```
q
0.800223231 0 0 0.800223231 0 0 cm
/CSp cs 0 0 0 scn
/GSa gs
BT
/F7 24 Tf 1 0 0 -1 0 0 Tm
236 -344 Td <0001> Tj
24 0 Td <0002> Tj
24 0 Td <0002> Tj
24 0 Td <0003> Tj
ET
Q
```
It goes to a new font (the Material-Icon font) at 24 point size, and appears to write "mood" _off_ the visible page (negative Y). I think the original coordinate system is flipped (Y=0 at top) and scaled:
```
0.750000000 0 0 -0.750000000 28.5000000 813.500000 cm
```
with a clipping window 717 wide x 1047 high. A good question would be why it's outputting "mood" instead of the icon, and another good question is where did those crazy coordinates come from?

Maybe that will give a clue to someone where to start looking...

**Comment by jofvr** [comment]
Resolved by add material like this : 
```css
@font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: url('./MaterialIcons-Regular.eot');
    /* For IE6-8 */
    src: url('./MaterialIcons-Regular.woff2') format('woff2'), url('./MaterialIcons-Regular.woff') format('woff'), url('./MaterialIcons-Regular.ttf') format('truetype');
}

.material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    /* Preferred icon size */
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;
    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;
    /* Support for IE. */
    font-feature-settings: 'liga';
}
```
