### ISSUE TITLE
Amazon Linux 2 server installation issue 

### ISSUE THREAD

**Issue by 65** [wkhtmltopdf/wkhtmltopdf#4996]
**wkhtmltopdf version(s) affected**: 0.12.6

Related to later comments on https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2251 

**OS information**
```
uname -a
4.14.225-169.362.amzn2.x86_64 #1 SMP Mon Mar 22 20:14:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

ElasticBeanstalk PHP 7.4 running on 64bit Amazon Linux 2/3.2.0

**Description**

When I run from command line on the server or from our web app we get 
```
/usr/local/bin/wkhtmltopdf https://www.google.com google.pdf
/usr/local/bin/wkhtmltopdf: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

**How to reproduce**

Here's the .ebextensions to install the package: 

```
commands:
  03_command:
    command: yum install --assumeyes zlib fontconfig freetype libX11 libXext libXrender xorg-x11-fonts-75dpi xorg-x11-fonts-Type1
  04_command:
    command: cd /tmp && wget --max-redirect 10 'https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm'
  05_command:
    command: cd /tmp && sudo yum install -y wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm
```

Amazon Linux has libpng installed
```
yum info libpng
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed Packages
Name        : libpng
Arch        : x86_64
Epoch       : 2
Version     : 1.5.13
Release     : 8.amzn2
Size        : 594 k
Repo        : installed
```

How do we get this working?

**Comment by 65** [comment]
For the benefit of others, until the AmazonLinux2 build works, I resolved this with the following .ebextensions file

```
commands:
  01_wget_wkhtmltox_0.12.2.1_linux-centos6-amd64:
    command: sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm
    test: test ! -f /usr/local/bin/wkhtmltopdf
  02_install_wkhtmltox_0.12.2.1_linux-centos6-amd64:
    command: sudo yum install -y wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm
    test: test ! -f /usr/local/bin/wkhtmltopdf
  03_install_libpng12:
    command: sudo yum install libpng12.x86_64
```

**Comment by michalzubkowicz** [comment]
With current version enough was:
`container_commands:
    1_install_wkhtmltopdf_requirments:
        command: yum -y install fontconfig libXrender libXext xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi freetype libpng zlib libjpeg-turbo openssl icu libX11 wkhtmltox
        ignoreErrors: true`

**Comment by gezoond** [comment]
amazon-linux-extras install epel -y
yum -y  install wkhtmltopdf

**Comment by cavasinf** [comment]
> amazon-linux-extras install epel -y yum -y install wkhtmltopdf

Currently epel is linked to the 0.12.4-1
```
wkhtmltopdf.x86_64                     0.12.4-1.el7                  epel
wkhtmltopdf-devel.x86_64               0.12.4-1.el7                  epel
```

If you want to use the last version `0.12.6-1` (with patched qt),
you can do it like that:
> ./.ebextensions/wkhtmltox.config
```yaml
packages:
    yum:
        libXext.x86_64: [ ]
        libXrender.x86_64: [ ]
        libXtst.x86_64: [ ]

commands:
    01_wget_wkhtmltox:
        command: sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm
    02_install_wkhtmltox:
        command: sudo rpm -i -F ./wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm

```

- `rpm -F` is used to:
  1. Freshen package 
  2. Removes `already installed` error.
- Removed `test: test ! -f /usr/local/bin/wkhtmltopdf` in case you want to upgrade to a newer version, this test will skip the needed version if an older version already installed.
