### ISSUE TITLE
Styling difference between [Windows and Linux]

### ISSUE THREAD

**Issue by TreasureJim** [wkhtmltopdf/wkhtmltopdf#5069]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
Ubuntu 20.04.2 LTS & Windows 10 Pro

**Description**
Using pdfkit wrapper for python to generate pdfs using wkhtmltopdf. 
Generating PDF in Linux works as expected however when trying to generate PDFs from same HTML file the css flex does not align divs on same line like it would in Linux. 
The image is on a seperate line underneath the text: "Usage Report"

**How to reproduce**
HTML file: 
```html
<!DOCTYPE html>
<html>
  <head>
    <link href="template.css" rel="stylesheet">
  </head>

  <body>
    <!-- HEADER  -->
    <div class="title-holder">
      <p class="title">Usage Report</p>
      <div class="company-logo">
        <img
          src="https://uploads-ssl.webflow.com/5f3acb2672fdcd05b7611500/5fdb9e7105edc00d5378b856_kafkalogo-p-800.jpeg"
        />
      </div>
    </div>

    <div class="title-holder">
      <p class="customer">Google Inc.</p>
      <div>
        <p id="subheader">Reporting Period</p>
        <p>08/07/2021 - 08/07/4021</p>
      </div>
    </div>

    <br />
    <hr />
  </body>
</html>
```

CSS file: 
```css
* {
  margin: 0;
  padding: 0;
  font-family: "AvenirNext-Light", "Avenir Next Light", "Avenir Next",
  sans-serif;
}

body {
  font-size: 100%;
  padding: 50px;
  background: #fff;
}

.title-holder {
  display: flex;
  justify-content: space-between;
}
.title {
  width: 60%;
  font-size: 3em;
  color: rgb(43, 143, 134);
  font-weight: bold;
}
.company-logo {
  width: 40%;
  text-align: right;
}
.company-logo img {
  width: 70%;
}

.customer {
  font-size: 1.5em;
}
```

Python script generating PDFs: 
```python
import pdfkit

pdfkit.from_file(
    r"report-template.html",
    r"test.pdf",
    options={
        "enable-local-file-access": None,
        "disable-smart-shrinking": None,
        # "zoom": "0.1"
    },
    css=r"template.css")
```

_File locations have been changed for privacy_

**Expected behavior**
PDF should be generating the image logo on the same line as the text: "Usage Report". Window generated PDFs should be matching Linux generated PDFs. 

Chrome Render of PDF: 
![Chrome Render](https://user-images.githubusercontent.com/71513440/129837854-eec6326a-e589-47fb-bea0-e86c7ecccb10.png)

Linux generated PDF: 
![Linux PDF Generation](https://user-images.githubusercontent.com/71513440/129838296-5e10539d-d937-4693-9b00-538306832ecd.png)

Windows broken PDF: 
![Windows PDF Generation](https://user-images.githubusercontent.com/71513440/129838349-8ccac93c-31da-475e-bbad-3a86aa42d4a3.png)

**Possible Solution**  
Originally thought it was due to DPI scaling differences in operating systems and monitors however this seems to have been fixed since Issue #2893 and adding `disable-smart-shrinking` and small `zoom` settings doesn't seem to fix the problem.
