### ISSUE TITLE
The same background image has blur

### ISSUE THREAD

**Issue by dadazhouRenee** [wkhtmltopdf/wkhtmltopdf#5153]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
windows 10

**Description**
The same background image  first element of them is blur, other are clear
![5ac0705c7e0164a03bd67bf7252b3c2](https://user-images.githubusercontent.com/31841446/146703304-e179383f-b820-4ed9-8d58-c7e037f578b3.png)
![40a4df1503f441f89fc34fb213a2d7c](https://user-images.githubusercontent.com/31841446/146703356-1c61dcac-ed7a-41b6-880b-f62fe17d9384.png)
`css:`
```css
.risk-level {
    span {
      background: url('../images/risk-level.png') no-repeat center;
      background-size:16px 16px;
      width: 20px;
      height:16px;
      display: inline-block;
    }
 }
```
**Expected behavior**
all of them are clear

**Possible Solution**  
It only appears in the first element.
