### ISSUE TITLE
Bootstrap v5.2.0 exception with custom properties

### ISSUE THREAD

**Issue by DevdevdevA** [wkhtmltopdf/wkhtmltopdf#5246]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
CentOS

**Description**
I upgraded from Bootstrap 4.6.0 to version 5.2.0 and since then some elements are not displayed correctly when generating the PDF. 
I investigated the bug and I have the impression that it is the custom properties that are not interpreted by wkhtmltopdf. 
Custom properties is an experimental feature on some browsers (https://developer.mozilla.org/fr/docs/Web/CSS/--*).

An example with bootstrap alerts (5.2.0) with custom properties:
```css
.alert {
  --bs-alert-bg: transparent;
  --bs-alert-padding-x: 1rem;
  --bs-alert-padding-y: 1rem;
  --bs-alert-margin-bottom: 1rem;
  --bs-alert-color: inherit;
  --bs-alert-border-color: transparent;
  --bs-alert-border: 1px solid var(--bs-alert-border-color);
  --bs-alert-border-radius: 0.375rem;
  background-color: var(--bs-alert-bg);
  border: var(--bs-alert-border);
  border-radius: var(--bs-alert-border-radius);
  color: var(--bs-alert-color);
  margin-bottom: var(--bs-alert-margin-bottom);
  padding: var(--bs-alert-padding-y) var(--bs-alert-padding-x);
  position: relative;
}
```
**How to reproduce**

```html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Test Bootstrap PDF</title>
  </head>
  <body>
    <h1>Test Bootstrap PDF</h1>
	<div class="alert alert-primary" role="alert">
	  A simple primary alert—check it out!
	</div>
  </body>
</html>
```
